# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='coorX',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='coorY',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
