# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170519_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=9)),
                ('weather', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='map',
            name='coorX',
            field=models.DecimalField(decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='coorY',
            field=models.DecimalField(decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Tag'),
        ),
    ]
