# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20170520_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['date']},
        ),
    ]
