# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20170520_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tags',
        ),
        migrations.AddField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(to='diary.Tag'),
        ),
    ]
