# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20170520_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tags',
        ),
    ]
