# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_remove_diary_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=20)),
                ('uploadDate', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='.media/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('psw', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=20)),
                ('ved', models.FileField(upload_to='media/')),
            ],
        ),
    ]
