# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_image_user_vedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='vedio',
            name='ved',
            field=models.FileField(upload_to='media'),
        ),
    ]
