# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20170521_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='image/None/no-img.jpg', upload_to='image/'),
        ),
    ]
