# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20170521_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to='image/'),
        ),
    ]
