# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_auto_20170522_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='diary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diary.Diary'),
        ),
    ]
