# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_map_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='diary',
        ),
        migrations.AddField(
            model_name='diary',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='diary',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.Map'),
        ),
        migrations.AddField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(to='diary.Tag'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
